### ISSUE TITLE
div within unordered list not showing

### ISSUE THREAD

**Issue by LordZUL** [imd1005-web-development-winter-2023/assignment-02-LordZUL#2]
@neilmispelaar 
Hello Neil!
Quick question, why is my three links (sign in, register and basket ) of banner not showing up on the page config of the GitHub setting?

There are two possible reasons, one being its a div within a list (not sure if I can do that).

Another is that I imported icon font links from Boxicons. (If that's the issue, should I make a transparent PNG from adobe and then import to image file? Or is there a way to fix that on GitHub using icon links?)

Thanks,
Alanna

**Comment by LordZUL** [comment]
oh wait never mind, it was just lagging on my end. I am so sorry Neil

**Comment by neilmispelaar** [comment]
Hi @LordZUL 

Unfortunately, you aren't allowed to put a `<div>` as a direct child under a `<ul>`.

You could instead put a class on the `<li>` to then style that `<li>` as you want or style a `<div>` inside your `<li>`. 

```html 
<ul>
  <li>...</li>
  <li>...</li>
  <li>...</li>

  <!-- Style the list item --> 
  <li class="style-for-list-item">...</li>
  
  <!-- Style the div inside the list item --> 
  <li>
     <div class="style-for-list-item-contents">
     ...
     </div>
   </li>
</ul>
```

## W3C Validation Test

https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-LordZUL%2F

<img width="1582" alt="Screenshot 2023-02-21 at 10 02 45 PM" src="https://user-images.githubusercontent.com/9325038/220510565-7551fb4e-a21a-4cdc-9b06-41c8a48dadb5.png">

**Comment by neilmispelaar** [comment]
Also @LordZUL 

No need to apologize! 

Please create as many issues as you need and tag me in any questions you may have.
