### ISSUE TITLE
Google Chrome not opening file correctly on GitHub

### ISSUE THREAD

**Issue by LordZUL** [imd1005-web-development-winter-2023/assignment-02-LordZUL#3]
Hello Neil @neilmispelaar ,

I don't know why but on Google, GitHub didn't properly register my footer and about section... But Firefox works? 

If google also have weird layout on your end, please open the page layout on FireFox!

Thank you,
Alanna

**Comment by neilmispelaar** [comment]
Hi @LordZUL 

Looking amazing! 

Here is what I see in Safari, and I'll drop a screenshot for Firefox in another comment.  

![Screen Shot 2023-02-26 at 22 31 38](https://user-images.githubusercontent.com/9325038/221466629-c52506b4-6ef3-4005-8e5c-00ceb265713c.jpg)

![Screen Shot 2023-02-26 at 22 33 33](https://user-images.githubusercontent.com/9325038/221466846-7cf970df-c369-43fd-8941-1b9b7c68ea51.png)

**Comment by neilmispelaar** [comment]
And here is Firefox

![Screenshot 2023-02-26 at 22-30-11 Assignment 02](https://user-images.githubusercontent.com/9325038/221467089-3ff6d325-32df-4f8a-b087-78a4724d9eb6.jpg)

**Comment by neilmispelaar** [comment]
Hi @LordZUL 

Just checked your code in the validator, there are a couple of small errors, it's possible the `width 200` item could be causing an issue somewhere. The second issue is around spaces in your image file name (there shouldn't be any spaces)

Here is the link to see the results: (don't worry about the warnings or info items) 

https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-LordZUL%2F


<img width="1559" alt="Screenshot 2023-02-26 at 10 39 15 PM" src="https://user-images.githubusercontent.com/9325038/221467666-4e1b241f-e0b2-4d61-83ac-2c3d28e03974.png">
